spring.application.name=demo
# Настройка базы данных в памяти (не нужно устанавливать БД)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Показывать SQL запросы в консоли (удобно для отладки)
spring.jpa.show-sql=true

# Включаем консоль для просмотра базы данных
spring.h2.console.enabled=true
server.port=9090